# Generated by Django 2.2.9 on 2020-01-30 03:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eventos', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='evento',
            table='evento',
        ),
    ]
