# Generated by Django 2.2.9 on 2020-01-30 04:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventos', '0002_auto_20200129_2224'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evento',
            name='tipo',
            field=models.CharField(blank=True, choices=[('p', 'Presencial'), ('v', 'Virtual')], default='c', help_text='Tipo de evento', max_length=1),
        ),
    ]
